[package]
name = "sui-proc-macros"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "fold", "extra-traits"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
proc-macro2 = "1"

[target.'cfg(msim)'.dependencies]
msim-macros = { git = "https://github.com/MystenLabs/mysten-sim.git", rev = "fdd2fd154ec88ddba30a3698c0a9ace01cf0dcb7", package = "msim-macros" }
